//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerRequest
    {
        public int IdAnswer { get; set; }
        public int IdTypeSent { get; set; }
        public System.Guid IdUser { get; set; }
        public int IdRequest { get; set; }
        public string IdStaff { get; set; }
        public int IdRead { get; set; }
        public string TitleSent { get; set; }
        public string ContentSent { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual ReadUser ReadUser { get; set; }
        public virtual RequestUser RequestUser { get; set; }
        public virtual TypeSentUser TypeSentUser { get; set; }
        public virtual User User { get; set; }
    }
}
