//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerComment
    {
        public int IdAnswer { get; set; }
        public int IdComment { get; set; }
        public System.Guid IdUser { get; set; }
        public string ContentAnswer { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual CommentMusic CommentMusic { get; set; }
        public virtual User User { get; set; }
    }
}
