//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirthdayUser
    {
        public int Id { get; set; }
        public System.Guid IdUser { get; set; }
        public string TitleSent { get; set; }
        public string ContentSent { get; set; }
        public System.DateTime BirthdayUser1 { get; set; }
        public System.DateTime DateSent { get; set; }
        public bool StatusSent { get; set; }
        public Nullable<System.Guid> T_UsersIdUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
