//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentMusic
    {
        public CommentMusic()
        {
            this.AnswerComments = new HashSet<AnswerComment>();
        }
    
        public int IdComment { get; set; }
        public System.Guid IdMusic { get; set; }
        public System.Guid IdUser { get; set; }
        public string ContentComment { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual ICollection<AnswerComment> AnswerComments { get; set; }
        public virtual Music Music { get; set; }
        public virtual User User { get; set; }
    }
}
