//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileMusic
    {
        public int IdFile { get; set; }
        public System.Guid IdMusic { get; set; }
        public string NameFile { get; set; }
        public byte[] DataFile { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string MimeType { get; set; }
        public byte[] DataFieImage { get; set; }
        public string NameImage { get; set; }
        public string TypeImage { get; set; }
    
        public virtual Music Music { get; set; }
    }
}
