//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HappyBirthdayStaff
    {
        public int Id { get; set; }
        public System.Guid IdUser { get; set; }
        public int IsStatusSent { get; set; }
        public string TitleSent { get; set; }
        public string ContentSent { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual StatusHappyBirthDayStaff StatusHappyBirthDayStaff { get; set; }
        public virtual User User { get; set; }
    }
}
