//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageQRCore
    {
        public int IdQRcore { get; set; }
        public System.Guid IdMusic { get; set; }
        public string TitleImage { get; set; }
        public byte[] ImageData { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual Music Music { get; set; }
    }
}
