//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public System.Guid IdLogin { get; set; }
        public System.Guid IdUser { get; set; }
        public System.DateTime DateLogin { get; set; }
        public System.DateTime TimeLogin { get; set; }
        public System.DateTime TimeSignout { get; set; }
    }
}
