//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public Music()
        {
            this.CommentMusics = new HashSet<CommentMusic>();
            this.DowloadMusics = new HashSet<DowloadMusic>();
            this.FileMusics = new HashSet<FileMusic>();
            this.ImageQRCores = new HashSet<ImageQRCore>();
            this.LikeMusics = new HashSet<LikeMusic>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public System.Guid IdMusic { get; set; }
        public string NoMusic { get; set; }
        public string NameMusic { get; set; }
        public string AuthorMusic { get; set; }
        public int IdSeason { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int IdStatusMusic { get; set; }
        public System.Guid IdUser { get; set; }
        public string IdStaff { get; set; }
        public System.DateTime TimeCreate { get; set; }
        public int IdSaints { get; set; }
        public int Date { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public string TokenData { get; set; }
    
        public virtual ICollection<CommentMusic> CommentMusics { get; set; }
        public virtual ICollection<DowloadMusic> DowloadMusics { get; set; }
        public virtual ICollection<FileMusic> FileMusics { get; set; }
        public virtual ICollection<ImageQRCore> ImageQRCores { get; set; }
        public virtual ICollection<LikeMusic> LikeMusics { get; set; }
        public virtual Sainte Sainte { get; set; }
        public virtual Season Season { get; set; }
        public virtual StatusMusic StatusMusic { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
