//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagerMusicDatabaseEntities : DbContext
    {
        public ManagerMusicDatabaseEntities()
            : base("name=ManagerMusicDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public DbSet<ActiverAccount> ActiverAccounts { get; set; }
        public DbSet<AnswerComment> AnswerComments { get; set; }
        public DbSet<AnswerGmailRequestPassword> AnswerGmailRequestPasswords { get; set; }
        public DbSet<AnswerRequest> AnswerRequests { get; set; }
        public DbSet<AppRoleClaim> AppRoleClaims { get; set; }
        public DbSet<AppUserClaim> AppUserClaims { get; set; }
        public DbSet<AppUserLogin> AppUserLogins { get; set; }
        public DbSet<AppUserRole> AppUserRoles { get; set; }
        public DbSet<AppUserToken> AppUserTokens { get; set; }
        public DbSet<BirthdayUser> BirthdayUsers { get; set; }
        public DbSet<ChatImageStaff> ChatImageStaffs { get; set; }
        public DbSet<ChatStaff> ChatStaffs { get; set; }
        public DbSet<City> Citys { get; set; }
        public DbSet<CommentMusic> CommentMusics { get; set; }
        public DbSet<DeleteNotification> DeleteNotifications { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<DowloadMusic> DowloadMusics { get; set; }
        public DbSet<FileMusic> FileMusics { get; set; }
        public DbSet<FilePlan> FilePlans { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<HappyBirthdayStaff> HappyBirthdayStaffs { get; set; }
        public DbSet<HistoryRole> HistoryRoles { get; set; }
        public DbSet<ImageQRCore> ImageQRCores { get; set; }
        public DbSet<LeverUser> LeverUsers { get; set; }
        public DbSet<LikeMusic> LikeMusics { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Marriage> Marriages { get; set; }
        public DbSet<Music> Musics { get; set; }
        public DbSet<NotificationPlan> NotificationPlans { get; set; }
        public DbSet<NotificationUser> NotificationUsers { get; set; }
        public DbSet<PlanStaff> PlanStaffs { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<ReadUser> ReadUsers { get; set; }
        public DbSet<ReceiveRequest> ReceiveRequests { get; set; }
        public DbSet<RequestPassword> RequestPasswords { get; set; }
        public DbSet<RequestUser> RequestUsers { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Sainte> Saintes { get; set; }
        public DbSet<Season> Seasons { get; set; }
        public DbSet<StaffOrUser> StaffOrUsers { get; set; }
        public DbSet<StatusHappyBirthDayStaff> StatusHappyBirthDayStaffs { get; set; }
        public DbSet<StatusMusic> StatusMusics { get; set; }
        public DbSet<StatusPlan> StatusPlans { get; set; }
        public DbSet<StatusRole> StatusRoles { get; set; }
        public DbSet<StatusSainte> StatusSaintes { get; set; }
        public DbSet<StatusSeason> StatusSeasons { get; set; }
        public DbSet<StatusStaffOff> StatusStaffOffs { get; set; }
        public DbSet<T_UpdateMusics> T_UpdateMusics { get; set; }
        public DbSet<TypeSentUser> TypeSentUsers { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ViewNotification> ViewNotifications { get; set; }
    }
}
