//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationPlan
    {
        public int Id { get; set; }
        public int IdPlan { get; set; }
        public System.Guid IdUser { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Content { get; set; }
        public bool StatusView { get; set; }
    }
}
