//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanStaff
    {
        public int IdPlan { get; set; }
        public string NamePlan { get; set; }
        public string ContentPlan { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.Guid IdUserPlan { get; set; }
        public System.Guid IdUserRequest { get; set; }
        public System.DateTime DateComplete { get; set; }
        public int IdStatusPlan { get; set; }
        public int AcceptPlan { get; set; }
        public System.TimeSpan TimeComplete { get; set; }
        public bool TimeUp { get; set; }
    }
}
