//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadUser
    {
        public ReadUser()
        {
            this.AnswerRequests = new HashSet<AnswerRequest>();
        }
    
        public int IdRead { get; set; }
        public string ReadContent { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual ICollection<AnswerRequest> AnswerRequests { get; set; }
    }
}
