//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestUser
    {
        public RequestUser()
        {
            this.AnswerRequests = new HashSet<AnswerRequest>();
        }
    
        public int IdRequest { get; set; }
        public System.Guid IdUser { get; set; }
        public string TitleRequest { get; set; }
        public string ContentRequest { get; set; }
        public System.DateTime DateRequest { get; set; }
        public Nullable<System.DateTime> DateHandled { get; set; }
        public Nullable<System.DateTime> DateSuccess { get; set; }
        public int IdReceiveRequest { get; set; }
        public Nullable<int> IdTypeSent { get; set; }
    
        public virtual ICollection<AnswerRequest> AnswerRequests { get; set; }
        public virtual ReceiveRequest ReceiveRequest { get; set; }
        public virtual User User { get; set; }
    }
}
