//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public System.Guid IdRole { get; set; }
        public int IdStatusRole { get; set; }
        public string SymbolRole { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string NormalizedName { get; set; }
        public string ConcurrencyStamp { get; set; }
    
        public virtual StatusRole StatusRole { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
