//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sainte
    {
        public Sainte()
        {
            this.Musics = new HashSet<Music>();
        }
    
        public int IdSaints { get; set; }
        public string NameSaints { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int IdStatusSaints { get; set; }
        public string IdStaff { get; set; }
        public string TokenData { get; set; }
        public System.Guid IdUser { get; set; }
    
        public virtual ICollection<Music> Musics { get; set; }
        public virtual StatusSainte StatusSainte { get; set; }
    }
}
