//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusHappyBirthDayStaff
    {
        public StatusHappyBirthDayStaff()
        {
            this.HappyBirthdayStaffs = new HashSet<HappyBirthdayStaff>();
        }
    
        public int IsStatusSent { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual ICollection<HappyBirthdayStaff> HappyBirthdayStaffs { get; set; }
    }
}
