//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UpdateMusics
    {
        public int Id { get; set; }
        public System.Guid IdMusic { get; set; }
        public System.Guid IdUser { get; set; }
        public string TokenData { get; set; }
        public string FileNameOld { get; set; }
        public string FileNameNew { get; set; }
        public string NameMusicOld { get; set; }
        public string NameMuiscNew { get; set; }
        public string AuthorOld { get; set; }
        public string AuthorNew { get; set; }
        public int IdSeasonOld { get; set; }
        public int IdSaintOld { get; set; }
        public int IdSeasonNew { get; set; }
        public int IdSaintNew { get; set; }
        public System.DateTime DateUpdate { get; set; }
    }
}
