//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeSentUser
    {
        public TypeSentUser()
        {
            this.AnswerRequests = new HashSet<AnswerRequest>();
        }
    
        public int IdTypeSent { get; set; }
        public string NameType { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<AnswerRequest> AnswerRequests { get; set; }
    }
}
