//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Learn.ConnectionDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AnswerComments = new HashSet<AnswerComment>();
            this.AnswerRequests = new HashSet<AnswerRequest>();
            this.BirthdayUsers = new HashSet<BirthdayUser>();
            this.CommentMusics = new HashSet<CommentMusic>();
            this.HappyBirthdayStaffs = new HashSet<HappyBirthdayStaff>();
            this.LikeMusics = new HashSet<LikeMusic>();
            this.Musics = new HashSet<Music>();
            this.NotificationUsers = new HashSet<NotificationUser>();
            this.Ratings = new HashSet<Rating>();
            this.RequestUsers = new HashSet<RequestUser>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public System.Guid IdUser { get; set; }
        public string IdStaff { get; set; }
        public int IdAccountActiver { get; set; }
        public int IdLever { get; set; }
        public int IdStaffOrUser { get; set; }
        public Nullable<int> StatusStaffOff { get; set; }
        public Nullable<int> IdMarriage { get; set; }
        public int IdGender { get; set; }
        public int IdCity { get; set; }
        public int IdDistrict { get; set; }
        public Nullable<System.DateTime> DateStaffOff { get; set; }
        public Nullable<System.DateTime> DateAccountBlock { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Date { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int Age { get; set; }
        public byte[] ImageAvata { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string AddressSatff { get; set; }
        public string PhoneStaff { get; set; }
        public Nullable<int> CancelHideStaff { get; set; }
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTimeOffset> LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string FullName { get; set; }
        public string TokenData { get; set; }
        public int TotalChat { get; set; }
        public bool WasView { get; set; }
        public string NameFile { get; set; }
        public string TypeImage { get; set; }
    
        public virtual ActiverAccount ActiverAccount { get; set; }
        public virtual ICollection<AnswerComment> AnswerComments { get; set; }
        public virtual ICollection<AnswerRequest> AnswerRequests { get; set; }
        public virtual ICollection<BirthdayUser> BirthdayUsers { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<CommentMusic> CommentMusics { get; set; }
        public virtual District District { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<HappyBirthdayStaff> HappyBirthdayStaffs { get; set; }
        public virtual LeverUser LeverUser { get; set; }
        public virtual ICollection<LikeMusic> LikeMusics { get; set; }
        public virtual Marriage Marriage { get; set; }
        public virtual ICollection<Music> Musics { get; set; }
        public virtual ICollection<NotificationUser> NotificationUsers { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<RequestUser> RequestUsers { get; set; }
        public virtual StaffOrUser StaffOrUser { get; set; }
        public virtual StatusStaffOff StatusStaffOff1 { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
